sudo: false
language: node_js
node_js:
- stable
- '0.12'
- '0.10'
before_install:
- openssl aes-256-cbc -K $encrypted_499dfc5dccdc_key -iv $encrypted_499dfc5dccdc_iv
  -in client-secret.json.enc -out client-secret.json -d
install: true
script:
- echo "No script to run"
deploy:
  provider: gae
  keyfile: client-secret.json
  project: kollabo-1194
  verbosity: debug
  default: true
  
